### PR TITLE
Fix/qa 110/jin hao/must see listing creation

### PR DESCRIPTION
**Pull request by JinHao-K**
14/7/21 - completed C1406.

### CODE REVIEW

**Comment by daniamrtha** [comment]
do you change any test suite file? @JinHao-K

**Comment by JinHao-K** [comment]
> do you change any test suite file? @JinHao-K

By test suite do you mean the testng.xml? If so then yes i changed it to run the 5 TCs for regular listing creation

**Comment by JinHao-K** [comment]
This photo was used to upload for all rooms to prevent the TCs from flaking

IMG-20210109-WA0006

**Comment by daniamrtha** [comment]
okay, I think you can make new suite test file (.xml) for listing creation first. Before add them on testng.xml @JinHao-K

**Pull request closed without merging**
